- pom.xml
- src/main/java/info/ata4/bsplib/struct/DDispInfo.java
- src/main/java/info/ata4/bspsrc/BspSource.java
- src/main/java/info/ata4/bspsrc/modules/geom/FaceSource.java
(Recreated request #35 but from a separate branch as I should have originally)
Displacement surface flags are not saved in the decompiled vmf, which means such displacements are always collidable regardless of their status in the input bsp. I used the following snippet from `hl2sdk-csgo\public\builddisp.cpp` to determine how to extract the flags.
```cpp
if ( ( minTess & 0x80000000 ) != 0 )
{
// If the high bit is set, this represents FLAGS (SURF_NOPHYSICS_COLL, etc.) flags.
int nFlags = minTess;
nFlags &= ~0x80000000;
GetSurface()->SetFlags( nFlags );
}
```
> Support displacement surface flags

- src/main/java/info/ata4/bsplib/BspFileReader.java
- src/main/java/info/ata4/bsplib/struct/DBrush.java
- src/main/java/info/ata4/bspsrc/modules/texture/TextureBuilder.java
- src/main/java/info/ata4/bspsrc/modules/texture/TextureSource.java
- src/main/java/info/ata4/bspsrc/modules/texture/ToolTexture.java
I've implemented a simple fix that allows grenade clips to be properly identified again.
However, the engine seems to be reusing an older, no longer in use, brush flag to mark them. This would probably cause problems in older engines which still use this brush flag.
Because of this and that I hadn't more games to test it on, i only activated this fix for Cs:Go.
The same applies for the blocklight fix. Only difference is that it uses a brush flag that is maybe used differently in other engines. Which is why i activated this fix only for  Cs:Go as well.
This fixes issues like described here: #44
> Csgo grenade clip/blocklight fix

- src/main/java/info/ata4/bspsrc/modules/entity/EntitySource.java
Static props don't have their 'Render in Fast Reflections' set, due to no implementation for it.
In CSGO the option uses the 'SCREEN_SPACE_FADE' flag, which was previously used for a now obsolete option, Screen Space Fade.
I've changed that this flag is used for 'Render in Fast Reflections' instead of 'Screen Space Fade' if the game is CSGO.
> Fixed 'Render in Fast Reflections' of static props not being set correctly for CSGO

- src/main/java/info/ata4/bsplib/util/VectorUtil.java
- src/main/java/info/ata4/bsplib/vector/Vector2f.java
- src/main/java/info/ata4/bsplib/vector/Vector3f.java
- src/main/java/info/ata4/bspsrc/gui/BspSourceFrame.form
- src/main/java/info/ata4/bspsrc/gui/BspSourceFrame.java
- src/main/java/info/ata4/bspsrc/modules/entity/EntitySource.java
- src/main/java/info/ata4/bspsrc/modules/texture/TextureBuilder.java
- src/main/java/info/ata4/bspsrc/util/AreaportalMapper.java
- src/main/java/info/ata4/bspsrc/util/OccluderMapper.java
- src/main/java/info/ata4/bspsrc/util/Winding.java
- src/main/java/info/ata4/bspsrc/util/WindingFactory.java
- test/maps/test_areaportals.vmf
The previous method for manually mapping areaportals was still very heavily relying on the ordering of brushes/areaportals. I've implemented a new algorithm, which now calculates probabilities to get correct mappings.
At its core it's very simple. Every areaportal brush is compared against all available areaportals. For each we calculate the probability that the brush represents it. The probability is based on the surface area they 'share'. So for example, if the brush doesn't even touch the areaportal, the probability would obviously be 0. If they do touch, we get the intersection area of the brushside and the areaportal and calculate it's surface area. The final probability is determined by dividing this surface area with the surface area of the areaportal.
Other than that I did some …
> Refactor 'Manual mode' of AreaportalMapper and general fixes/cleanup to OccluderMapper

- src/main/java/info/ata4/bspsrc/modules/texture/TextureBuilder.java
The blocklight fix, which got previously implemented with https://github.com/ata4/bspsrc/commit/e0ad93effaaff3221021cad195a9b868d75da884, was only enabled for cs:go because it was only tested on this game.
I tested the fix on two additional games, Garrysmod and Portal 2. Both work perfectly fine, so I enabled the fix for every game.
In combination with #48, fixes #44.
> Enabled blocklight fix for every game

- src/main/java/info/ata4/bspsrc/modules/VmfMeta.java
I've made a small change to the vmf writing process. It fixes the IndexOutOfBoundsException that was being thrown when trying to decompile maps without an entity lump.
Fixes #53
> Fixed IndexOutOfBoundsException when decompiling maps without entity lump

- src/main/java/info/ata4/bsplib/BspFileReader.java
- src/main/java/info/ata4/bsplib/app/SourceAppID.java
- src/main/java/info/ata4/bsplib/struct/DStaticPropV11.java
- src/main/java/info/ata4/bsplib/struct/DStaticPropV11lite.java
- src/main/java/info/ata4/bspsrc/modules/entity/EntitySource.java
This PR adds better static prop support for Black Mesa across all the different branches/releases of Black Mesa.
I have added a struct class for an older version of the V11 static prop struct, which I named `DStaticPropV11lite`, and changed the `DStaticPropV11` to extend the `DStaticPropV11lite` class.
I have also added support for writing the key-values for the `m_DiffuseModulation` struct field, but only if the values are anything other than the default. The key-values in question are "rendercolor" and "renderamt", which set the fade color (R G B) and fade alpha (A), respectively. These key-values aren't defined in BM's base.fgd. Therefore, I'm not sure if they have any practical use. There is, however, one stock map (bm_c2a5g) that has a few static props where the `m_DiffuseModulation` …
> Add better static prop support for Black Mesa

- src/main/resources/info/ata4/bsplib/app/appdb.xml
Updated the file pattern for Black Mesa in the app database (appdb.xml) to include Xen and multiplayer maps.
**Note:** The RegEx pattern includes maps starting with "dm_", which may possibly affect detection of multiplayer maps for other games.
> Update file pattern for Black Mesa in appdb.xml

- src/main/java/info/ata4/bspsrc/modules/entity/EntitySource.java
This fixes a minor bug where the brush "sides" list in info_overlay entity blocks has a space delimiter before the closing quotation mark.
The change involves employing the use of StringJoiner instead of Stringbuilder for building the brush sides list in the writeOverlays() method in EntitySource. There is a similar loop in the writeCubemaps() method, except here the last space is deleted from the string afterwards. I changed the code here as well for consistency.
Alternatively, we could use Java 8 streams, but I think it performs slightly slower than the for loop with StringJoiner:
```Java
String s = sides.stream()
.map(String::valueOf)
.collect(Collectors.joining(" "));
```
> Fix trailing space in brush sides list

- src/main/java/info/ata4/bsplib/struct/DDispInfo.java
Support for displacement surface flags was added with PR #39.
However, Black Mesa maps often have the DISP_INFO_FLAG_HAS_MULTIBLEND flag enabled on displacements, which gets written to the displacement flags property along with the surface collision flags. It should be cleared from the return value of getSurfaceFlags() as it is not a surface collision flag. I have confirmed that this flag is not present in the original vmf.
I believe this change is safe to implement for all games, since it either applies to, or has no impact on other games.
> Clear multiblend flag from disp surface info flags

- src/main/java/info/ata4/bspinfo/gui/BspInfoFrame.java
- src/main/java/info/ata4/bspsrc/gui/BspSourceFrame.java
- src/main/java/info/ata4/util/gui/FileDrop.java
Refactor FileDrop constructors to use Consumer<File[]> instead of inner interface. Remove the unused interface, replace existing anonymus implementations with lambdas.
> Refactor FileDrop Constructors

- src/main/java/info/ata4/bsplib/app/SourceApp.java
- src/main/java/info/ata4/bspsrc/modules/texture/TextureSource.java
There was a very weird issue, where when your pc language was set to Turkish you'd often end up with missing textures. For some reason, every texture name had all `i` characters converted to `?` characters. 
The source of the problem seems to be, that texture names are converted using `String.toLowerCase()`, which uses the standard locale. If this happens to be the Turkish locale, the `I` character is not converted to `i`, as you would expect from the English language, but to `ı`. [This due to the Turkish language having 2 `I` characters. The "Dotted I" (U+0069) and the "Dotles I" (U+0131).](http://www.i18nguy.com/unicode/turkish-i18n.html)
I changed the toLowerCase conversion to always use the `Locale.ROOT` locale instead of the standard one.
Fixes #51
> Fixed missing textures with languages like Turkish

- src/main/java/info/ata4/bsplib/BspFileReader.java
- src/main/java/info/ata4/bsplib/struct/DStaticPropV6VIN.java
- src/main/java/info/ata4/bspsrc/modules/entity/EntitySource.java
This PR adds support for vindictus prop scaling.
This in its self isn't really useful, because vindictus doesn't have an official SDK but this may help people, who want to port a specific map to another game which does supports prop scaling.
The scaling is saved for the static prop as a made up property named `scale`.
Fixes #62
> Implemented support for vindictus prop scaling

- src/main/java/info/ata4/bsplib/nmo/NmoFile.java
This is a minor change of how nmos files from the game 'No More Room in Hell' are written.
Instead of first writing to a fixed size ByteBuffer, this takes advantage of the DataWriter class and directly writes to the file.
> Minor change in nmos file writing process

- src/main/java/info/ata4/bsplib/BspFileReader.java
- src/main/java/info/ata4/bsplib/app/SourceAppID.java
- src/main/java/info/ata4/bsplib/struct/DStaticPropV10CSGO.java
- src/main/java/info/ata4/bspsrc/modules/entity/EntitySource.java
- src/main/resources/info/ata4/bsplib/app/appdb.xml
This includes:
- Basic detection of the game via entity type recognition.
- Support for its static prop lump
Because Insurgency is based of the csgo engine branch, it's static prop lump is identical to the one from csgo. This makes the implementation easy, because we can just reuse `DStaticPropV10CSGO`.
One fix was needed though. The change, that `screenSpaceFade` was obsoleted and replaced for `RenderInFastReflection` instead (implemented in bae568549fdd5f272b002056b4253e9a714bdef0) was only active if the actual **game** was csgo. I changed this to be always active if the `DStaticPropV10CSGO` implementation is used.
Closes #73
> Feature: Add support for 'Insurgency'

- src/main/java/info/ata4/bspsrc/modules/VmfMeta.java
- src/main/java/info/ata4/bspsrc/modules/entity/EntitySource.java
- src/main/java/info/ata4/bspsrc/util/AreaportalMapper.java
- src/main/java/info/ata4/util/AlphanumComparator.java
This includes:
- Sorting visgroups by their name for better readability.
- Support for visgroup colors.
- Unused visgroups are no longer written to the vmf
Visgroups are now sorted by their name using a custom String Comparator. It's called `AlphanumComparator` and tries to create a more 'human-like' sorting algorithm by separating a string into multiple chunks. A chunk can either be a digit or just a normal string. This makes it possible to compare digits by their literal value.
**Comparison of de_inferno from csgo:**
| No sorting | String Comparator| Alphanum Comparator  |
| --- | --- | --- |
| ![no-sorting](https://user-images.githubusercontent.com/19492038/70857297-08faf100-1eec-11ea-85f1-779c79419baa.PNG) | ![normal](https://user-images.githubusercontent.com/19492038/70857394-b0c4ee80 …
> Improvments to visgroup writting

- src/main/java/info/ata4/bsplib/struct/DBrush.java
- src/main/java/info/ata4/bspsrc/modules/BspDecompiler.java
- src/main/java/info/ata4/bspsrc/modules/entity/EntitySource.java
- src/main/java/info/ata4/bspsrc/modules/geom/BrushSource.java
- src/main/java/info/ata4/bspsrc/modules/texture/TextureBuilder.java
In contrast to other games (Left 4 Dead, Cs:s, Garrys mod...), csgo doesn't use the `func_ladder` entity to create ladders but rather Vbsp automatically converts brushes with `tools/toolsinvisibleladder` material applied to ladders. More information can be found here: [https://developer.valvesoftware.com/wiki/Working_Ladders](https://developer.valvesoftware.com/wiki/Working_Ladders)
This pull request adds support for this 'non-object' brush based ladder system for csgo.
Additionally, `fixToolTexture()` now correctly reapplies `tools/toolsinvisibleladder` to all ladder brushes.
> Add ladder support for csgo

- pom.xml
In order to use JDK 9 or later for compiling bspsrc, but still compile for Java 8, the Apache Maven Compiler Plugin has been configured to use the '--release' command-line option instead of '-source' and '-target' with javac. This ensures that the compiled program will not accidentally use APIs that are only available in the Java version corresponding to the JDK in use.
The Apache Maven Compiler Plugin and the Apache Maven Shade Plugin have also been updated to their current versions.
Fixes #83
> Update JDK and Apache Maven

- src/main/java/info/ata4/bsplib/util/VectorUtil.java
- src/main/java/info/ata4/bspsrc/modules/entity/EntitySource.java
- src/main/java/info/ata4/bspsrc/util/AreaportalMapper.java
Previously the decompiler crashed, when calling `VectorUtil.internalMatchingAreaPercentage` with an invalid Winding. This was because the method made the assumption, that the provided windings at least contained 3 vertices.
This pr adds a check to that method, returning 0 in cases where the provided windings are invalid.
Additionally error handling with areaportal and occluder writing was improved.
Fixes #85
> Fix exception with invalid areaportal/occluder data

- src/main/java/info/ata4/bsplib/util/VectorUtil.java
- src/main/java/info/ata4/bspsrc/util/AreaportalMapper.java
- src/main/java/info/ata4/util/JavaUtil.java
This pr fixes a `NoSuchElementException` sometimes being thrown in the `Manual` areaportal reallocating method.
Additionally, some changes were also made to the `Ordered` mode, to make it a little more robust.
Fixes: #88
> Fix NoSuchElementException when reallocating areaportals of certain maps

- pom.xml
- src/main/java/info/ata4/bspinfo/gui/BspInfoFrame.java
- src/main/java/info/ata4/bspinfo/gui/models/EmbeddedTableModel.java
- src/main/java/info/ata4/bsplib/BspFile.java
- src/main/java/info/ata4/bsplib/PakFile.java
- src/main/java/info/ata4/bsplib/io/LzmaUtil.java
- src/main/java/info/ata4/bsplib/lump/AbstractLump.java
- src/main/java/info/ata4/bspsrc/BspSource.java
- src/main/java/info/ata4/bspsrc/modules/BspCompileParams.java
- src/main/java/info/ata4/bspsrc/modules/BspProtection.java
- src/main/java/info/ata4/bspsrc/modules/texture/TextureSource.java
- src/main/java/info/ata4/bspunprotect/BspUnprotect.java
Extracting of embedded resources is currently handled by Apache Commons Compress, which however doesn't support the zip compression method 14 (lzma). This compression method is used in games like Team Fortress 2. The pull request manually adds support for that compression method.
Important to note is, that I switched the lzma decompressing library from [ata4/lzmajio](https://github.com/ata4/lzmajio) to another one called [xz for java](https://tukaani.org/xz/java.html) (also used by common compress for lzma file compression/decompression). I made this change because `xz for java` has a better support for lzma input/output streams, which I needed. It is, however, entirely possible to implement the current code with the old library `ata4/lzmajio`, so if that needed, I could make the required …
> Add support for lzma zip compression method (14)

- src/main/java/info/ata4/bsplib/BspFileReader.java
- src/main/java/info/ata4/bsplib/struct/DStaticPropV6VIN.java
- src/main/java/info/ata4/bsplib/struct/DStaticPropV7VIN.java
- src/main/java/info/ata4/bsplib/struct/DStaticPropVinScaling.java
- src/main/java/info/ata4/bspsrc/modules/entity/EntitySource.java
Adds support for Vindictus sprp version 7 (DStaticPropV7VIN), which is identical to the **standard** version 6 (DStaticPropV6), but like it’s own version 6 (DStaticPropV6VIN), has an additional array of scaling vectors before the static prop array.
Fixes: #91
> Add support for Vindictus sprp version 7

- src/main/java/info/ata4/bspsrc/modules/BspDecompiler.java
- src/main/java/info/ata4/bspsrc/modules/VmfMeta.java
The decompiler automatically adds `Decompiled by BSPSource..` as a map comment to the vmf. If, however, the map already has a comment, the decompiler incorrectly writes two comments into the final vmf.
This pull request is a simple fix, so that the `Decompiled by BSPSource..` is simply appended to the comment instead of creating a second one.
> Fix duplicated map comment

- src/main/java/info/ata4/bsplib/vector/Vector2f.java
- src/main/java/info/ata4/bspsrc/util/AreaportalMapper.java
- src/main/java/info/ata4/bspsrc/util/ConvexPolygon.java
- src/main/java/info/ata4/bspsrc/util/OccluderMapper.java
- src/main/java/info/ata4/bspsrc/util/VectorUtil.java
With #57 I introduced the `VectorUtil` class used for the Areaportal/Occluder mapper. The purpose of its methods is to compare `Windings` by their surface area and get the overlap as a percentage. Internally this is done by first testing if both windings share a common plane and then converting them to 2 dimensional convex polygons to make comparison easy.
Previously, all relevant calculations were all done in the `VectorUtil` class. To make the class less bloated with methods, this pr transfers some of that code into a new class called `ConvexPolygon`. As the name already suggest, this is a class which represents a convex polygon defined by a list of vertex positions.
Additionally, there are also some improvements to the javadoc and the algorithm for testing if a position is inside a …
> VectorUtil refactor

- src/main/java/info/ata4/bspsrc/util/WindingFactory.java
The `WindingFactory` class uses maps to cache already calculated windings.
While all methods use their respective `DStruct` as keys in the cache, `fromSide()` uses a hash based on the `DBrush` and the `DBrushSide`. This approach however doesn't account for hash collisions. If a `DBrush` + `DBrushSide` combination produces the same hash as a different `DBrush` + `DBrushSide` combination, the method incorrectly assumes their equal and returns the already calculated winding.
The pull request fixes this by simply using a Key-Value pair class as keys in the cache.
This probably resolves #56 as it seems to have been caused by this.
> Fix improper hash collision handling in WindingFactory

- src/main/java/info/ata4/bspsrc/modules/entity/EntitySource.java
`disableselfshadowing`, `disablevertexlighting`, `ignorenormals` are all properties defined in DStaticPropV4 but were only written if versions DStaticPropV5 or DStaticPropV6 where present.
This pr is a simple fix for that.
> Fix some incorrectly written static prop attributes

- src/main/java/info/ata4/bsplib/BspFileReader.java
When creating 4-way blend displacements, the multi blend information is stored in the `LUMP_DISP_MULTIBLEND` lump, which is located at the index 63.
Bspsrc already correctly reads this lumps and converts the information into the resulting vmf.
Black Mesa however, doesn't store the `LUMP_DISP_MULTIBLEND`  lump at index 63, but rather at 61 which caused all multi blend information to be lost. The original lump located at index 61 doesn't seem to be used by the game.
This PR simply introduces 2 checks in the bsp file reading part to circumvent this issue.
1. `loadDispMultiBlend()` now uses the lump at index 61 (`LUMP_OVERLAY_SYSTEM_LEVELS`) if the game is Black Mesa.
2. `loadOverlays()` now simply saves an empty list to `bspData.overlaySysLevels` if the game is Black Mesa, instead of reading …
> Fix Black Mesa 4-way blend decompiling

- src/main/java/info/ata4/bsplib/app/SourceAppID.java
- src/main/java/info/ata4/bspsrc/modules/texture/TextureBuilder.java
- src/main/java/info/ata4/bspsrc/modules/texture/TextureSource.java
- src/main/java/info/ata4/bspsrc/modules/texture/ToolTexture.java
- src/main/java/info/ata4/bspsrc/modules/texture/ToolTextureMatcher.java
- src/main/java/info/ata4/bspsrc/modules/texture/tooltextures/ToolTextureDefinition.java
- src/main/java/info/ata4/bspsrc/modules/texture/tooltextures/ToolTextureSet.java
- src/main/java/info/ata4/bspsrc/modules/texture/tooltextures/definitions/CsgoToolTextureDefinitions.java
- src/main/java/info/ata4/bspsrc/modules/texture/tooltextures/definitions/CssToolTextureDefinition.java
- src/main/java/info/ata4/bspsrc/modules/texture/tooltextures/definitions/SourceToolTextureDefinition.java
In the vbsp compilation process some brushsides get their texture name changed. This is caused vbsp trying to save space in the texinfo lump by reusing different texinfos. The algorithm for compacting texinfos can be looked up [here](https://github.com/ValveSoftware/source-sdk-2013/blob/0d8dceea4310fde5706b3ce1c70609d72a38efdf/sp/src/utils/vbsp/writebsp.cpp#L768), but I'll summarize the gist of it.
If the texinfo object of a brushside **is not** referenced by any face in the face lump, the algorithm tries to find and apply a "similar" texinfo object, which **is** referenced by a face. This primarily affects tooltextures (or probably all materials with `SURF_NODRAW`), as those are invisible and consequently don't need to generate any faces.
The previous algorithm in bspsrc used …
> Refactor tooltexture fixing system

- scripts/bspsrc.sh
There is no `javaw` executable in the Linux's JDK
> Use java instead of javaw on Linux
